name = "edit_distance"
version = "2.0.0"
description = "A pure Gleam package to compute the edit distance of two strings"

licences = ["Apache-2.0"]
repository = { type = "github", user = "giacomocavalieri", repo = "edit_distance" }
gleam = ">= 0.32.0"
#Â links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = "~> 0.32"

[dev-dependencies]
gleeunit = "~> 0.10"
blah = "~> 0.10"
